### ISSUE TITLE
Crawling CC using the Webgraph 

### ISSUE THREAD

**Issue by akul-goyal** [commoncrawl/cc-webgraph#11]
Hi,

I am interested in gathering data from common crawl using the webgraph as a metric for webpage similarity. So far, I have recreated parts of the webgraph and am using the following code to download WET files from the common crawl dataset:

```
from warcio import ArchiveIterator
import cdx_toolkit
import requests

def get_page_url(webURL):
	cdx = cdx_toolkit.CDXFetcher(source='cc')
	for obj in cdx.iter(webURL, limit=1):
		return wet_builder(obj['filename'])


def wet_builder(page_url):
	warc_url = f'https://commoncrawl.s3.amazonaws.com/{page_url}'
	wet_url = warc_url.replace('/warc/', '/wet/').replace('warc.gz', 'warc.wet.gz')
	r = requests.get(wet_url, stream=True)
	records = ArchiveIterator(r.raw)
	record = next(records)
	record = next(records)
	a = record.content_stream().read()
	retText= a.decode('utf-8')[:1000]
	r.close()
	return retText
```
However, this code runs slowly and requires each website to be passed in manually. Is there a faster (more native) way to crawl the webgraph and download each webpage's text content? I don't need to go through the entire webgraph, I am just looking to crawl through a subset of it.

**Comment by wumpus** [comment]
This is hard to do efficiently because we have not published an index of the WET files. You're using the cdx index correctly; if there was a WET index, this code would run as fast as just the get_page_url() does now.

**Comment by akul-goyal** [comment]
Ok! Understandable. Do you think this is the best I can do, or do you have any ideas on how I could speed up the code?

**Comment by wumpus** [comment]
I would download the html from the WARCs, using the index to make it relatively efficient, and then do the text extraction yourself. We use Apache Tika to do that.

**Comment by akul-goyal** [comment]
To generate the WARC links, I am using the following SQL: https://github.com/commoncrawl/cc-index-table/blob/main/src/sql/examples/cc-index/get-records-home-pages.sql, where instead of the alexa1M sites, I am filling it with the websites that I encounter in the webgraph. However, certain sites do not appear within the common crawl table for CC-MAIN-2023-50. For example: inese-poga.artistwebsites.com does not appear when I try directly searching for it as such:
```
SELECT *
FROM "ccindex"."ccindex" AS cc
WHERE cc.crawl = 'CC-MAIN-2023-50' 
AND cc.url_host_registered_domain = 'inese-poga.artistwebsites.com';
```
Am I missing something?

**Comment by akul-goyal** [comment]
For example, the website "com.westgateband" is found in the webgraph but I cannot find it within the common crawl table using the following SQL command:
```
SELECT *
FROM "ccindex"."ccindex" AS cc
WHERE cc.url_host_name = 'westgateband.com'
  AND cc.subset = 'warc';
```

**Comment by wumpus** [comment]
The webgraph is usually constructed using 3 crawls, and, there can be nodes in it that we did not crawl. That means that we found a link to that web host, somewhere.

**Comment by akul-goyal** [comment]
I see. Is there any easy way to figure out which webpages were not crawled without having to query athena with every webpage in the webgraph?

**Comment by wumpus** [comment]
Sorry, no. I do have a plan to have a "host level database" that includes that information, but I have no idea when we'll implement it.

**Comment by akul-goyal** [comment]
That is okay! I figured out how to get the needed WARC files. Is there a GitHub repo you recommend that converts the Warc files to extracted text?

**Comment by wumpus** [comment]
We use Tika3, but there are many other choices.
