### ISSUE TITLE
The latest `Webgraph` data?

### ISSUE THREAD

**Issue by liyucheng09** [commoncrawl/cc-webgraph#8]
My job needs to check whether given links are included in the a specific crawl.

I find [this](https://groups.google.com/g/common-crawl/c/XC2QmOE-sdI?pli=1) explaining how to access Webgraph data to go through all links in common crawl.

And I found [this](https://commoncrawl.org/search?query=webgraph) to search webgraph release in commoncrawl.org.

But I wonder do we have a place to access the latest `Webgraph` data? Instead of manually serach on coomoncrawl.org?

Or the links in Commoncrawl is quite the same among different crawls? So that it's safe to use not too fresh Webgraph data?

**Comment by wumpus** [comment]
https://commoncrawl.org/web-graphs now has a dropdown with the latest web graph at the top.

Thank you for bringing this to our attention!
